#!/bin/bash

# $ gsettings list-keys org.gnome.Ptyxis.Shortcuts | grep tab
dconf write /org/gnome/Ptyxis/Shortcuts/copy-clipboard "'<Super>c'"
dconf write /org/gnome/Ptyxis/Shortcuts/paste-clipboard "'<Super>v'"
dconf write /org/gnome/Ptyxis/Shortcuts/new-tab "'disabled'"
dconf write /org/gnome/Ptyxis/Shortcuts/new-window "'disabled'"
dconf write /org/gnome/Ptyxis/Shortcuts/close-tab "'disabled'"
dconf write /org/gnome/Ptyxis/Shortcuts/close-window "'disabled'"
dconf write /org/gnome/Ptyxis/Shortcuts/next-tab "'disabled'"
dconf write /org/gnome/Ptyxis/Shortcuts/previous-tab "'disabled'"
dconf write /org/gnome/Ptyxis/Shortcuts/move-next-tab "'disabled'"
dconf write /org/gnome/Ptyxis/Shortcuts/move-previous-tab "'disabled'"
dconf write /org/gnome/Ptyxis/Shortcuts/search "'disabled'"

dconf write /org/gnome/Ptyxis/Shortcuts/close-other-tabs "'disabled'"
dconf write /org/gnome/Ptyxis/Shortcuts/close-tab "'disabled'"
dconf write /org/gnome/Ptyxis/Shortcuts/detach-tab "'disabled'"
dconf write /org/gnome/Ptyxis/Shortcuts/focus-tab-1 "'disabled'"
dconf write /org/gnome/Ptyxis/Shortcuts/focus-tab-10 "'disabled'"
dconf write /org/gnome/Ptyxis/Shortcuts/focus-tab-2 "'disabled'"
dconf write /org/gnome/Ptyxis/Shortcuts/focus-tab-3 "'disabled'"
dconf write /org/gnome/Ptyxis/Shortcuts/focus-tab-4 "'disabled'"
dconf write /org/gnome/Ptyxis/Shortcuts/focus-tab-5 "'disabled'"
dconf write /org/gnome/Ptyxis/Shortcuts/focus-tab-6 "'disabled'"
dconf write /org/gnome/Ptyxis/Shortcuts/focus-tab-7 "'disabled'"
dconf write /org/gnome/Ptyxis/Shortcuts/focus-tab-8 "'disabled'"
dconf write /org/gnome/Ptyxis/Shortcuts/focus-tab-9 "'disabled'"
dconf write /org/gnome/Ptyxis/Shortcuts/focus-tab-last "'disabled'"
dconf write /org/gnome/Ptyxis/Shortcuts/move-next-tab "'disabled'"
dconf write /org/gnome/Ptyxis/Shortcuts/move-previous-tab "'disabled'"
dconf write /org/gnome/Ptyxis/Shortcuts/move-tab-left "'disabled'"
dconf write /org/gnome/Ptyxis/Shortcuts/move-tab-right "'disabled'"
dconf write /org/gnome/Ptyxis/Shortcuts/new-tab "'disabled'"
dconf write /org/gnome/Ptyxis/Shortcuts/tab-menu "'disabled'"
dconf write /org/gnome/Ptyxis/Shortcuts/tab-overview "'disabled'"
dconf write /org/gnome/Ptyxis/Shortcuts/undo-close-tab "'disabled'"
