# Key Code
# https://github.com/emberian/evdev/blob/8a498d41ec78ffd5f585bdfccbce82bb30295dcd/src/scancodes.rs#L99
shared:
  sleep: &sleep {sleep: 200}

modmap:
  - name: Global
    remap:
      CapsLock:
        alone: Esc
        held: Ctrl_L
      Esc: CapsLock

keymap:
  - name: Alacritty
    application:
      only: Alacritty
    remap:
      # Alt -> Ctrl
      Super-w: M-w
      Super-t: M-t
      Super-1: M-1
      Super-2: M-2
      Super-3: M-3
      Super-4: M-4
      Super-5: M-5
      Super-6: M-6
      Super-7: M-7
      Super-8: M-8
      Super-9: M-9

  - name: Firefox
    application:
      only: firefox_firefox
    remap:
      Super-1: M-1
      Super-2: M-2
      Super-3: M-3
      Super-4: M-4
      Super-5: M-5
      Super-6: M-6
      Super-7: M-7
      Super-8: M-8
      Super-9: M-9

      Super-R: C-R
      # mouse
      # Super-Btn_Left: C-Btn_Left
      Super-Btn_Left: [Btn_Right, *sleep, Key_Right, Enter] # workaround for the above

      C-n: Down
      C-p: Up

  - name: Emacs
    application:
      only: Emacs
    remap:
      Super-v: Shift-Insert
      Super-q: [C-x, C-c]
      Super-w: Super-w

  # - name: Slack
  #   application:
  #     only: Slack
  #   remap:
  #     Super-o: C-Shift-tab
  #     Super-p: C-tab
  #     Super-n: C-k
  #     Super-k: M-up
  #     Super-j: M-down
  #     C-M-k: Shift-Alt-up
  #     C-M-j: Shift-Alt-down

  #     Super-1: C-1
  #     Super-2: C-2
  #     Super-3: C-3
  #     Super-4: C-4
  #     Super-5: C-5
  #     Super-6: C-6
  #     Super-7: C-7
  #     Super-8: C-8
  #     Super-9: C-9

  - name: Default -- some of these are overridden by the above definitions
    remap:
      # Emacs word
      Super-b: C-left
      Super-f: C-right

      # Alt -> Ctrl
      Super-a: C-a
      Super-z: C-z
      Super-x: C-x
      Super-c: C-c
      Super-v: C-v
      Super-w: C-w
      Super-t: C-t
      Super-l: C-l

      Super-q: C-q
      Super-equal: C-equal
      Super-minus: C-minus
      Super-0: C-0

      Key_Sysrq: Btn_Left
      Key_ScrollLock: C-Shift-0
      Key_Pause: Btn_Right

      # # Tab changes + Alt-Enter simulation
      # Super-o: C-Shift-tab
      # Super-p: C-tab
      # Super-Enter: M-Enter

      # # actually these are vim insert mode bindings, but compatible with shell
      # C-w: [C-Shift-left, delete]

      # C-d: delete
      # Super-d: C-delete

      # # Underscore without Shift
      # RO: Shift-RO

      # # SKK hack for Chrome
      # C-j: C-m
