# Key Code
# https://github.com/emberian/evdev/blob/8a498d41ec78ffd5f585bdfccbce82bb30295dcd/src/scancodes.rs#L99
shared:
  sleep: &sleep {sleep: 100}

modmap:
  - name: Global
    remap:
      CapsLock:
        alone: Esc
        held: Ctrl_L
      Esc: CapsLock
  - name: Workarround Super+Space for toogle-overview
    application:
      only: firefox_firefox
    remap:
      Alt_L:
        held: Alt_R
        alone: Ctrl_R

keymap:
  - name: Alacritty
    application:
      only: Alacritty
    remap:
      # Alt -> Ctrl
      KEY_LEFTMETA-w: M-w
      KEY_LEFTMETA-t: M-t

      KEY_LEFTMETA-1: M-1
      KEY_LEFTMETA-2: M-2
      KEY_LEFTMETA-3: M-3
      KEY_LEFTMETA-4: M-4
      KEY_LEFTMETA-5: M-5
      KEY_LEFTMETA-6: M-6
      KEY_LEFTMETA-7: M-7
      KEY_LEFTMETA-8: M-8
      KEY_LEFTMETA-9: M-9

  - name: Firefox
    application:
      only: firefox_firefox
    remap:
      # Emacs word
      KEY_LEFTMETA-b: C-left
      KEY_LEFTMETA-f: C-right

      KEY_LEFTMETA-1: M-1
      KEY_LEFTMETA-2: M-2
      KEY_LEFTMETA-3: M-3
      KEY_LEFTMETA-4: M-4
      KEY_LEFTMETA-5: M-5
      KEY_LEFTMETA-6: M-6
      KEY_LEFTMETA-7: M-7
      KEY_LEFTMETA-8: M-8
      KEY_LEFTMETA-9: M-9

      KEY_LEFTMETA-r: C-R

      # mouse
      # KEY_LEFTMETA-Btn_Left: C-Btn_Left
      # M-Btn_Left: C-Btn_Left
      # Super-Btn_Left: C-Btn_Left

      KEY_LEFTMETA-Btn_Left: [Btn_Right, *sleep, Down, *sleep, Enter] # workaround for the above
      # M-Btn_Left: [Btn_Right, *sleep, Down, *sleep] # workaround for the above
      # M-Btn_Left: [Btn_Right, *sleep, *sleep, *sleep] # workaround for the above
      # M-Key_Sysrq: [Btn_Right, *sleep, Key_Right, Enter]
      # Btn_Extra: [Btn_Right, *sleep, Key_Right, Enter]

      C-n: Down
      C-p: Up

  - name: Antigravity
    application:
      only: antigravity
    remap:
      Super-f: C-f
      Super-s: C-s
  - name: Cursor
    application:
      only: Cursor
    remap:
      Super-s: C-s

  - name: Emacs
    application:
      only: emacs
    remap:
      M-v: Shift-Insert
      M-q: [C-x, C-c]
      M-w: Super-w
      M-s: Super-s
      M-1: Super-1
      M-2: Super-2
      M-3: Super-3
      M-4: Super-4
      M-5: Super-5
      M-6: Super-6
      M-7: Super-7
      M-8: Super-8
      M-9: Super-9
      M-0: Super-0

  # - name: Slack
  #   application:
  #     only: Slack
  #   remap:
  #     Super-o: C-Shift-tab
  #     Super-p: C-tab
  #     Super-n: C-k
  #     Super-k: M-up
  #     Super-j: M-down
  #     C-M-k: Shift-Alt-up
  #     C-M-j: Shift-Alt-down

  #     Super-1: C-1
  #     Super-2: C-2
  #     Super-3: C-3
  #     Super-4: C-4
  #     Super-5: C-5
  #     Super-6: C-6
  #     Super-7: C-7
  #     Super-8: C-8
  #     Super-9: C-9

  - name: Default -- some of these are overridden by the above definitions
    application:
      only: icloud-notes
    remap:
      Super-c: C-c
  - name: Default -- some of these are overridden by the above definitions
    application:
      not: [Emacs]
    remap:
      # Alt -> Ctrl
      KEY_LEFTMETA-a: C-a
      KEY_LEFTMETA-z: C-z
      KEY_LEFTMETA-x: C-x
      KEY_LEFTMETA-c: C-c
      KEY_LEFTMETA-v: C-v
      KEY_LEFTMETA-w: C-w
      KEY_LEFTMETA-t: C-t
      KEY_LEFTMETA-l: C-l

      KEY_LEFTMETA-q: C-q
      KEY_LEFTMETA-equal: C-equal
      KEY_LEFTMETA-minus: C-minus
      KEY_LEFTMETA-0: C-0

      Sysrq: Btn_Left
      ScrollLock: C-Shift-0
      Pause: Btn_Right

      # # Tab changes + Alt-Enter simulation
      # Super-o: C-Shift-tab
      # Super-p: C-tab
      # Super-Enter: M-Enter

      # # actually these are vim insert mode bindings, but compatible with shell
      # C-w: [C-Shift-left, delete]

      # C-d: delete
      # Super-d: C-delete

      # # Underscore without Shift
      # RO: Shift-RO

      # # SKK hack for Chrome
      # C-j: C-m
